version: '3'

services:
  inethi-user-managament-api:
    container_name: inethi-user-managament-api
    build: .
    command: bash -c "python manage.py runserver"
    ports:
      - "8000:8000"
    depends_on:
      - inethi-user-managament-mysql

  inethi-user-managament-mysql:
    container_name: inethi-user-managament-mysql
    platform: linux/x86_64
    image: mysql
    environment:
      MYSQL_DATABASE: 'inethi-user-managament-api'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/db:/var/lib/mysql